### ISSUE TITLE
Setup Jet Racer

### ISSUE THREAD

**Issue by ribeiroth** [SEAME-pt/Team04#43]
Install drivers

**Comment by danctorres** [comment]
wip PR to update documentation

**Comment by danctorres** [comment]
On hold.
SSH not working with current 42 network. A new network will be setup on the future.

**Comment by danctorres** [comment]
OS was flashed on the jetson board.
And we where able to connect via ssh.
Documentation was created describing the process.
Follow up tasks will be created to control the car (e.g. controlling the motors).

**Comment by danctorres** [comment]
Joao is picking up the problem and trying to solve SD card problems.
